language: cpp
sudo: required

compiler :
  - gcc
  - clang

addons:
  apt:
    sources:
      - sourceline: "deb http://deb.debian.org/debian buster main"
    packages:
      - cppcheck
      - iwyu

script:
  - mkdir protobuf
  - cd protobuf
  - wget https://github.com/google/protobuf/archive/v3.5.2.tar.gz
  - tar -xzvf v3.5.2.tar.gz
  - cd protobuf-3.5.2 && ./autogen.sh && ./configure && make && sudo make install
  - cd ../..
  - mkdir build
  - cd build
  - export LD_LIBRARY_PATH=/usr/local/lib
  - cmake -DCHECK_CODE=1 ..
  - make
  - make check

branches:
  only:
    - master

os:
  - linux
