#disable for now. travis' image are too old. :(
language: cpp
dist: trusty
sudo: required

script:
  - mkdir protobuf
  - cd protobuf
  - wget https://github.com/google/protobuf/archive/v3.5.2.tar.gz
  - tar -xzvf v3.5.2.tar.gz
  - cd protobuf-3.5.2 && ./autogen.sh && ./configure && make && sudo make install
  - cd ../..
  - mkdir build
  - cd build
  - export LD_LIBRARY_PATH=/usr/local/lib
  - cmake ..
  - make
  - make check

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cppcheck
            - iwyu
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
            - cppcheck
            - iwyu
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
    - eval "${MATRIX_EVAL}"
