language: cpp
dist: trusty
sudo: required

script:
  - mkdir protobuf
  - cd protobuf
  - wget https://github.com/google/protobuf/archive/v3.5.2.tar.gz
  - tar -xzvf v3.5.2.tar.gz
  - cd protobuf-3.5.2 && ./autogen.sh && ./configure && make -j`grep -c ^processor /proc/cpuinfo` && sudo make install
  - cd ../..
  - mkdir build
  - cd build
  - export LD_LIBRARY_PATH=/usr/local/lib
  - cmake ..
  - VERBOSE=1 make -j`grep -c ^processor /proc/cpuinfo`
  - VERBOSE=1 make check -j`grep -c ^processor /proc/cpuinfo`

branches:
  only:
    - master

env:
  global:
    - secure: "hhCAxq7xx7t95rZcLmw9I6Z538/ajeeP90JP9KD0Wmt3btjHsLTg92he6xpmIfKrLpaQCUF/tRPE5g2wfPQffDwTqZieslv4jj8AXPeNu4mf0r4iPHbEXF+zlIv8KTeYNgfWElVTU4jxE1T2bdwiQZCNJ6Nq30iGoXCwqxPrrv4ZjImKSibvY1cY+SQShXiKJbagritwRDcFcDH/9YjYDbml88YAJmTUC7tZUtr9D/HY9CxnbSMfMPzGE3RsGonMOJre+Z9jFTB4JZBEtWdkCtkdPyw9rla1QDxNyFhDN6ilhiM2puECGDQrNhO18Xl9elnbRGrFpQVsP+d9Ge2tZNHMUx6v0fEmnj2oJl3oUWUZtszp8mTycSIg6ffDEfV9eojowwZjDPhAbunu7Ao0/Vr80vhw7FhrlLxDA8IqPnWudHvu4W8snFmeZfUZ4s4LMwzBce3kli+OQ/tnaQF9UFqg8528bKmq8gG0O+qbuVCO/AGZQaYx2jKvNChS9oX27SpmkKvihEGOi0hjriWoHKvDE76kWKl0NP9mwFicVxl5L6817z2Y/nCGkq9BlsMSaVIgXO8r9mCJsx3m2fJTgbLaf3mma+wraO3mPF8U8DK73YUGpd50Sh5mrpznXOS9IuMlkHLU00CTQQ1B55Y4qC4wNbdkjDXe2vaJaom7mDg="
    - LD_LIBRARY_PATH=/usr/local/lib

addons:
  coverity_scan:
    project:
      name: my_github/my_project
      version: 1.0
      description: My Project
    build_command_prepend: mkdir protobuf; cd protobuf; wget https://github.com/google/protobuf/archive/v3.5.2.tar.gz; tar -xzvf v3.5.2.tar.gz; cd protobuf-3.5.2 && ./autogen.sh && ./configure && make -j`grep -c ^processor /proc/cpuinfo` && sudo make install; cd ../..; mkdir build; cd build; cmake ..
    build_command: make check
    branch_pattern: coverity_scan


matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cppcheck
            - iwyu
            - gdb
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

#    - os: linux
#      addons:
#        apt:
#          sources:
#            - llvm-toolchain-trusty-5.0
#          packages:
#            - clang-5.0
#            - cppcheck
#            - iwyu
#            - gdb
#      env:
#        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
    - eval "${MATRIX_EVAL}"
