language: cpp
sudo: required

compiler :
  - gcc
  - clang

addons:
  apt:
    packages:
      - cppcheck
      - iwyu

script:
  - mkdir protobuf
  - cd protobuf
  - wget https://github.com/google/protobuf/archive/v3.5.2.tar.gz
  - tar -xzvf v3.5.2.tar.gz
  - cd protobuf-3.5.2 && ./configure && make && sudo make install
  - cd ..
  - mkdir build
  - cd build
  - cmake -DCHECK_CODE=1 ..
  - make
  - make check

branches:
  only:
    - master

os:
  - linux
