language: cpp
sudo: false

compiler :
  - gcc
  - clang

addons:
  apt:
    sources:
      - sourceline: 'deb http://fr.archive.ubuntu.com/ubuntu/ artful main'
    packages:
      - cppcheck
      - clang
      - libprotobuf-dev
      - iwyu

script:
  - mkdir build
  - cd build
  - cmake -DCHECK_CODE=1 ..
  - make
  - make check

branches:
  only:
    - master

os:
  - linux
