language: cpp
sudo: false

compiler :
  - gcc
  - clang

addons:
  apt:
    sources:
      - alias: debian-stretch
      - sourceline: 'deb http://ftp.us.debian.org/debian unstable main contrib non-free'
      - key_url: https://ftp-master.debian.org/keys/archive-key-7.0.asc
    packages:
      - cppcheck
      - clang
      - libprotobuf-dev
      - binutils
      - iwyu

script:
  - mkdir build
  - cd build
  - cmake -DCHECK_CODE=1 ..
  - make
  - make check

branches:
  only:
    - master

os:
  - linux
